apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    tier: front-end

spec:
  template:
    metadata:
      Labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
    replicas: 3
    selector:
      matchLabels:
        type: front-end
