#Lecture 33
# map a service to a single pod

# kubectl create -f service-definition.yml
# kubectl get services
# curl http://x.x.x.x<nodeiP>:30008
apiVersion: v1
kind: Servcice


metadata: my-service

spec:
  type: NodePort #e.g CLusterIP LoadBalancer
  ports:
    - targetport: 80
      port: 80
      nodePort: 30008
  selector:
   app: myapp             # from metadata labels replicaset-pod.yaml
   type: front-app        # from metadata labels replicaset-pod.yaml


# map a service to a multi pod
# automatic load balancer based on labels
# Random Algorithm
# SessioAffinity: yes
# the service spans through all the nodes
# curl http://10.0.0.1:30008
# curl http://10.0.0.2:30008
# curl http://10.0.0.3:30008
# without any additional steps or configuration changes